spring.application.name=CurrencyExchange


spring.datasource.url=jdbc:postgresql://localhost:5252/exchange
spring.datasource.username=admin
spring.datasource.password=password


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect